### ISSUE TITLE
"EMPTY" printed on empty image state

### ISSUE THREAD

**Issue by ImTheSquid** [lorenzofiamingo/swiftui-cached-async-image#10]
There is a print statement [here](https://github.com/lorenzofiamingo/swiftui-cached-async-image/blob/dabd3bafa9917a264df5306be137c062143285ce/Sources/CachedAsyncImage/CachedAsyncImage.swift#L330) that I don't think should be included because having no URL is a valid state and the print doesn't seem to have any purpose. The current inclusion of the statement spams my console since I use this library to asynchronously load a list of users.

I'd personally like to see it removed or at least have it made toggleable so I don't have to see it.

As of 3/1/22 the master branch has this issue.

**Comment by lorenzofiamingo** [comment]
Sorry, this should not be present.

**Comment by lorenzofiamingo** [comment]
Solved in version [2.0.1](https://github.com/lorenzofiamingo/swiftui-cached-async-image/tree/2.0.1).
