### ISSUE TITLE
Cache does not work

### ISSUE THREAD

**Issue by khambir** [lorenzofiamingo/swiftui-cached-async-image#11]
I use version 2.0 and image caching does not work.

**Comment by lorenzofiamingo** [comment]
If you are using default cache, probably the image is too large to be saved, so use a custom one.
If you already using a custom one, make sure to specify it on `CachedAsyncImage` initialization and that it is big enough for the the images it will handle (`URLCache` stores images that have 5% max of its size)

**Comment by khambir** [comment]
I use this extension for specifying image size

```
// URLCache+imageCache.swift

extension URLCache {
    
    static let imageCache = URLCache(memoryCapacity: 512*1000*1000, diskCapacity: 10*1000*1000*1000)
}
```

And I set `.imageCache` in the initializer, but in `List` images always reload.

**Comment by lorenzofiamingo** [comment]
To be able to help you out I'll need a reproducible example.

**Comment by lorenzofiamingo** [comment]
Maybe the problem was you was using redirecting url. 2977899d51535b2ddbc410e01c102846ad78698b fixes this.
