### ISSUE TITLE
Question - Is an in-memory cache?

### ISSUE THREAD

**Issue by sebasira** [lorenzofiamingo/swiftui-cached-async-image#14]
I mean, will the image still be cached after I exit and re-enter the app, or is just while the app is "alive"? For example I open the app today, and then I open it again in the next month, will the image be still cached?

Thank you!

**Comment by lorenzofiamingo** [comment]
Both in-memory and on disk.

It's using the Foundation [URLCache](https://developer.apple.com/documentation/foundation/urlcache).

**Comment by nikolaydubina** [comment]
in my case, this library stores only in single active session. data does not persist across app restarts.

**Comment by lorenzofiamingo** [comment]
@nikolaydubina Have you set the cache? The response (in this case our image) must be no larger than about 5% of the disk cache. (See [this discussion](https://developer.apple.com/documentation/foundation/nsurlsessiondatadelegate/1411612-urlsession#discussion)). Also, On-disk cache may be purged when the system runs low on disk space.
